from __future__ import annotations
import math
import numpy as np
import pandas as pd

def enrich(df):
 d=df.copy(); d['EMA20']=d.Close.ewm(span=20,adjust=False).mean(); d['EMA50']=d.Close.ewm(span=50,adjust=False).mean(); delta=d.Close.diff(); gain=delta.clip(lower=0).ewm(alpha=1/14,adjust=False).mean(); loss=(-delta.clip(upper=0)).ewm(alpha=1/14,adjust=False).mean(); d['RSI']=100-100/(1+gain/loss.replace(0,np.nan)); d['MACD']=d.Close.ewm(span=12,adjust=False).mean()-d.Close.ewm(span=26,adjust=False).mean(); d['SIGNAL']=d.MACD.ewm(span=9,adjust=False).mean(); tr=pd.concat([(d.High-d.Low),(d.High-d.Close.shift()).abs(),(d.Low-d.Close.shift()).abs()],axis=1).max(axis=1); d['ATR']=tr.ewm(alpha=1/14,adjust=False).mean(); d['RET']=d.Close.pct_change(); d['VOL']=d.RET.rolling(20).std()*100; return d.fillna(method='bfill').fillna(0)
def build_agent_reports(d):
 x=d.iloc[-1]; recent=d.tail(30); rsi=float(x.RSI); momentum=(rsi-50)/25; trend=1 if x.Close>x.EMA20>x.EMA50 else -1 if x.Close<x.EMA20<x.EMA50 else 0; vol=float(x.VOL); atr=float(x.ATR); swing_high=float(recent.High.max()); swing_low=float(recent.Low.min()); breakout=1 if x.Close>swing_high-0.15*atr else -1 if x.Close<swing_low+0.15*atr else 0
 return {
 'Momentum':{'name':'Jarvis · Momentum Analyst','purpose':'Measures short-term price momentum without making the final decision.','score':round(max(-1,min(1,momentum)),2),'stance':'Positive' if momentum>.15 else 'Negative' if momentum<-.15 else 'Neutral','summary':f'RSI {rsi:.1f}; MACD spread {(x.MACD-x.SIGNAL):.2f}.','checks':[f'RSI(14): {rsi:.1f}',f'MACD: {x.MACD:.2f}',f'Signal line: {x.SIGNAL:.2f}','Recent close-to-close acceleration'],'evidence':[f'Last close {x.Close:.2f}',f'MACD histogram {(x.MACD-x.SIGNAL):.2f}'],'handoff':f'Momentum score {momentum:+.2f}; RSI {rsi:.1f}; watch for confirmation from trend and pattern agents.','limitations':'Momentum can reverse quickly and should not be used alone.'},
 'Trend':{'name':'Tom · Trend Analyst','purpose':'Checks directional structure using moving averages and swing behavior.','score':trend,'stance':'Positive' if trend>0 else 'Negative' if trend<0 else 'Mixed','summary':f'Close {x.Close:.2f}; EMA20 {x.EMA20:.2f}; EMA50 {x.EMA50:.2f}.','checks':['Close relative to EMA20','EMA20 relative to EMA50','Recent higher-high/lower-low structure'],'evidence':[f'EMA20 {x.EMA20:.2f}',f'EMA50 {x.EMA50:.2f}',f'30-bar range {swing_low:.2f}–{swing_high:.2f}'],'handoff':f'Trend score {trend:+.2f}; price structure is '+('aligned upward.' if trend>0 else 'aligned downward.' if trend<0 else 'not fully aligned.'),'limitations':'Moving averages lag and may react slowly during sharp reversals.'},
 'Volatility':{'name':'Criss · Risk & Volatility Analyst','purpose':'Measures movement size and derives a transparent risk distance.','score':round(-min(1,vol/1.5),2),'stance':'Elevated' if vol>.35 else 'Normal','summary':f'ATR {atr:.2f}; rolling return volatility {vol:.3f}%.','checks':['ATR(14)','20-bar return dispersion','Current candle range versus ATR'],'evidence':[f'ATR {atr:.2f}',f'Latest range {(x.High-x.Low):.2f}',f'Rolling volatility {vol:.3f}%'],'handoff':f'Use ATR {atr:.2f} for scenario boundaries; current volatility is '+('elevated.' if vol>.35 else 'within the recent range.'),'limitations':'Historical volatility does not predict gap risk or provider outages.'},
 'Pattern':{'name':'KD · Chart Pattern Analyst','purpose':'Checks recent support, resistance and breakout proximity.','score':breakout,'stance':'Breakout up' if breakout>0 else 'Breakdown' if breakout<0 else 'Range','summary':f'30-bar support {swing_low:.2f}; resistance {swing_high:.2f}.','checks':['30-bar swing high','30-bar swing low','Close proximity to range boundaries','EMA alignment confirmation'],'evidence':[f'Support {swing_low:.2f}',f'Resistance {swing_high:.2f}',f'Close {x.Close:.2f}'],'handoff':f'Pattern score {breakout:+.2f}; price is '+('testing resistance.' if breakout>0 else 'testing support.' if breakout<0 else 'inside the recent range.'),'limitations':'Pattern classification is rule-based and can produce false breakouts.'},
 'News':{'name':'Harry · News & Macro Analyst','purpose':'Reports whether an external news feed is connected.','score':0,'stance':'Unavailable','summary':'No licensed news feed is configured in this build.','checks':['News connector status','Timestamp freshness','Source availability'],'evidence':['No external headlines were retrieved','News score excluded from consensus'],'handoff':'News context unavailable; Supervisor must reduce confidence and avoid claiming a news-based conclusion.','limitations':'This agent cannot assess macroeconomic headlines until a licensed news API is connected.'}}
def supervisor_consensus(d,reports):
 x=d.iloc[-1]; scores=[reports[k]['score'] for k in ['Momentum','Trend','Volatility','Pattern']]; weighted=.3*scores[0]+.3*scores[1]+.15*scores[2]+.25*scores[3]; atr=max(float(x.ATR),.01); label='BULLISH SCENARIO' if weighted>.22 else 'BEARISH SCENARIO' if weighted<-.22 else 'NO-TRADE / WAIT'; direction=1 if weighted>.22 else -1 if weighted<-.22 else 0; entry=float(x.Close); stop=entry-direction*1.35*atr if direction else entry-atr; target=entry+direction*2.2*atr if direction else entry+atr; confidence=min(78,max(35,int(48+abs(weighted)*35-8)))
 rationale=f"Specialists produced a weighted consensus score of {weighted:+.2f}. Momentum is {reports['Momentum']['stance'].lower()}, trend is {reports['Trend']['stance'].lower()}, pattern state is {reports['Pattern']['stance'].lower()}, and news context is unavailable. The scenario is therefore {label.lower()} with reduced confidence."
 return {'label':label,'score':round(weighted,2),'entry':round(entry,2),'stop':round(stop,2),'target':round(target,2),'confidence':confidence,'rationale':rationale}
